# generated by configure / remove this line to disable regeneration
prefix="/usr/local"
exec_prefix="${prefix}"
bindir="${exec_prefix}/bin"
libdir="/home/majsterklepka/git/libiban/.libs"
datarootdir="${prefix}/share"
datadir="${datarootdir}"
sysconfdir="${prefix}/etc"
includedir="/home/majsterklepka/git/libiban/."
package="libiban"
suffix=""

for option; do case "$option" in --list-all|--name) echo  "libiban"
;; --help) pkg-config --help ; echo Buildscript Of "libiban Library"
;; --modversion|--version) echo "2.1"
;; --requires) echo : ""
;; --libs) echo -L${libdir} "" "-llibiban -lgmp"
       :
;; --cflags) echo -I${includedir} "-I/usr/local/include/libiban"
       :
;; --variable=*) eval echo '$'`echo $option | sed -e 's/.*=//'`
;; --uninstalled) exit 0 
;; *) ;; esac done
